[build]
  # 让Netlify在线构建Vue应用
  command = "cd sansen_planner_vue && npm ci && npm run build"
  # 发布整个项目根目录
  publish = "."

[build.environment]
  # 指定Node.js版本
  NODE_VERSION = "18"

# SPA路由重定向配置 - sansen_planner_vue  
# 强制重定向到构建后的dist目录，避免加载源文件
[[redirects]]
  from = "/sansen_planner_vue"
  to = "/sansen_planner_vue/dist/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/sansen_planner_vue/"
  to = "/sansen_planner_vue/dist/index.html"
  status = 200
  force = true

# 排除静态资源的重定向 - 让这些文件正常提供服务
[[redirects]]
  from = "/sansen_planner_vue/assets/*"
  to = "/sansen_planner_vue/dist/assets/:splat"
  status = 200

[[redirects]]
  from = "/sansen_planner_vue/dist/*"
  to = "/sansen_planner_vue/dist/:splat"
  status = 200

# SPA路由重定向（除了上述静态资源）
[[redirects]]
  from = "/sansen_planner_vue/*"
  to = "/sansen_planner_vue/dist/index.html"
  status = 200
  force = false

# 注意：sansen_planner_vuetify 目录不存在，已移除相关配置

# 抛硬币工具 - 静态HTML，无需特殊配置，但确保正确访问
[[redirects]]
  from = "/coin_flip"
  to = "/coin_flip/"
  status = 301

# 静态资源缓存配置
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML文件不缓存，确保更新及时
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# 安全头配置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block" 